# See https:#eslint.org/docs/user-guide/configuring
parserOptions:
  # Parse with latest JavaScript version
  ecmaVersion: "latest"
# Ignore files that can't be parsed as valid JS
ignorePatterns:
  - chart/copy_example_vg.html
# Add all global variables in the browser, as well as $/jQuery.
# This handles the most common use of JavaScript in projects.
env:
  browser: true
  jquery: true
globals:
  _: readonly
  anchors: readonly
  ClipboardJS: readonly
  g1: readonly
  moment: readonly
  Sentry: readonly
  SwaggerUIBundle: readonly
# Check JS inside HTML files. Strips Tornado templates {{ ... }}, {% ... %}, etc
plugins: [html, template]
# Use eslint recommended rules by default
extends: eslint:recommended
# Issue a warning when JS functions are too complex
rules:
  complexity: ["warn", { max: 10 }]
